site_name: toytree documentation
site_url: https://eaton-lab.org/toytree
repo_url: https://github.com/eaton-lab/toytree
edit_uri: edit/master/docs/pages/
docs_dir: docs/pages

theme:
  favicon: assets/favicon.svg
  icon:
    logo: material/graph-outline

plugins:
  - search

extra_css:
  - css/notebook-markdown.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Getting started:
      - Home: index.md
      - Installation: installation.md
      - Change log: change_log.md
      - Contribute: contribute.md
      - Citation: citation.md

  - User Guide:
      - 'Quick Guide': quick_guide.md
      - 'Tree I/O':
          - parsing tree data: parse_trees.md
          - writing tree data: write_trees.md

      - 'Core Concepts':
          - Node: core-node.md
          - ToyTree: core-toytree.md
          - MultiTree: core-multitree.md
          - Traversal: core-traversal.md
          - Node query/selection: core-query.md
          - Data/Features: core-data.md

      - 'Drawing':
          - drawing basics: drawing-basics.md
          - drawing options: drawing-options.md
          - coordinates and axes: drawing-coordinates.md
          - built-in tree styles: drawing-tree-styles.md
          - save/export drawings: drawing-save.md
          - range-mapping data: drawing-range-mapping.md
          - color-mapping data: drawing-color-mapping.md
          - multitree draw grid: drawing-mtree-grid.md
          - multitree draw cloud: drawing-mtree-cloud.md

      - '[annotate]':
          - add_edges: anno-add-edges.md
          - add_tip_labels: anno-add_tip_labels.md

      - '[mod]':
          - rooting:
            - outgroup: mod-rooting-outgroup.md
            - mad - minimal ancestor deviation: mod-rooting-mad.md
            - dlc - duplication loss coalescence: mod-rooting-dlc.md
          - topology changes: mod-topology.md
          - edge/dist changes: mod-edges.md
          - make ultrametric: mod-make-ultrametric.md

      - '[distance]':
          - tree distances: distance-tree.md
          - node distances: distance-node.md

      - '[infer]':
          - consensus trees: infer-consensus.md
          - neighbor joining: infer-neighbor-joining.md
          - upgma: infer-upgma.md
          - parsimony indices: infer-parsimony.md
          - duplication loss coalescence: infer-dlc.md

      - '[pcm]':
          - simulate traits: pcm-simulate.md
          - fit discrete CMTC: ...
          - fit continuous ML: ...
          - fit pgls (Gaussian): ...
          - fit pglm (non-Gaussian): ...
          - ancestral state reconstruction: ...
          - stochastic map: ...
          - phylogenetic anova: ...
          - phylogenetic signal: ...
          - vcv matrix: ...

      - '[enum]':
          - bipartitions: ...
          - quartets: ...
          - quadripartitions: ...
          - enumerations: ...

      - '[network]':
          - parse networks: ...
          - draw networks: ...

  - 'Command Line': command-line.md

    # - Species/Demographic Trees: ...
    # - Admixture/Networks: ... # TO DO



  - Cookbooks:
      - CLI pipelines: cli-pipelines.md
      - Debug canvas: debug-canvas.md

  - FAQs: FAQs.md
