#!/usr/bin/env python

"""Random Tree generation functions. Uses numpy RNG."""

from typing import Iterable, Optional

import numpy as np
import pandas as pd

from toytree.core.node import Node
from toytree.core.tree import ToyTree
from toytree.utils import ToytreeError

# pylint: disable=invalid-name, too-many-branches, too-many-statements


def _assign_names(
    tree: ToyTree,
    random: bool,
    rng: np.random.Generator,
    names: Optional[Iterable] = None,
) -> None:
    """Set tip names on a tree in place."""
    if names is None:
        labels = [f"r{nidx}" for nidx in range(tree.ntips)]
    else:
        labels = [str(i) for i in names]
        if len(labels) != tree.ntips:
            raise ValueError(f"len(names)={len(labels)} does not match ntips={tree.ntips}.")

    if random:
        order = rng.permutation(tree.ntips)
        for nidx, lidx in enumerate(order):
            tree[nidx].name = labels[int(lidx)]
    else:
        for nidx, name in enumerate(labels):
            tree[nidx].name = name


def rtree(
    ntips: int,
    random_names: bool = False,
    seed: Optional[int] = None,
    names: Optional[Iterable] = None,
) -> ToyTree:
    """Return a random bifurcating topology.

    The default settings for Node support (np.nan) and dist (1.0) can
    be further modified after generating the tree. The topology is
    generated by repeatedly selecting a current tip uniformly at random
    and splitting it into two children.

    Parameters
    ----------
    ntips: int
        Number of tips in the tree. Must be an integer >= 2.
    random_names: bool
        If True then tip names are randomized rather than ordered.
    seed: Optional[int]
        An integer seed for the numpy random number generator.
    names: Optional[Iterable]
        Optional tip labels. If provided, its length must equal ``ntips``.
        Names are assigned in idx order unless ``random_names=True``.

    Example
    -------
    >>> tree = toytree.rtree.rtree(ntips=10, seed=123)
    """
    if isinstance(ntips, bool) or not isinstance(ntips, int):
        raise ToytreeError("ntips must be an integer >= 2.")
    if ntips < 2:
        raise ToytreeError("ntips must be >= 2.")
    names_seq = None if names is None else list(names)
    if names_seq is not None and len(names_seq) != ntips:
        raise ValueError(f"len(names)={len(names_seq)} does not match ntips={ntips}.")

    # seed generator
    rng = np.random.default_rng(seed)

    # generate random topology with N tips.
    root = Node()
    current_tips = [root]

    # add children n-1 times, updating who the current children are.
    for _ in range(ntips - 1):
        # remove a random tip in O(1) via swap-pop.
        ridx = int(rng.integers(0, len(current_tips)))
        tip = current_tips[ridx]
        current_tips[ridx] = current_tips[-1]
        current_tips.pop()
        child0 = Node(dist=1.)
        child1 = Node(dist=1.)
        tip._add_child(child0)
        tip._add_child(child1)
        current_tips.extend([child0, child1])

    # Root edge is represented by the two root-child edges.
    # Split this edge length evenly so each side is 0.5.
    for child in root.children:
        child._dist = 0.5

    # assign tip labels as r{idx} for leaf nodes.
    tree = ToyTree(root)
    _assign_names(tree, random_names, rng, names=names_seq)
    return tree


def unittree(
    ntips: int,
    treeheight: float = 1.0,
    random_names: bool = False,
    seed: Optional[int] = None,
    names: Optional[Iterable] = None,
) -> ToyTree:
    """Return an ultrametric tree where internal edges are all 1.

    A random tree is generated by iteratively splitting edges with
    equal probability. All internal edges are set to dist=1, and
    external edges are extended to make the tree ultrametric. The
    total tree height can be scaled to any arbitrary height, and
    other Nodes are scaled proportionately.

    Parameters
    ----------
    ntips: int
        The number of tips in the tree.
    treeheight: float
        All nodes in the tree will be scaled to retain relative node
        heights when scaling the total tree height to a new age.
    random_names: bool
        If True then names on the tips are randomized, else they are
        set to match with the node idx order.
    seed: Optional[int]
        An integer seed for the np random number generator.
    names: Optional[Iterable]
        Optional tip labels. If provided, its length must equal ``ntips``.
        Names are assigned in idx order unless ``random_names=True``.

    Examples
    --------
    >>> tree = toytree.rtree.unittree(ntips=10, treeheight=1e6)
    """
    if isinstance(treeheight, bool) or not isinstance(treeheight, (int, float, np.number)):
        raise ToytreeError("treeheight must be a numeric value > 0.")
    treeheight = float(treeheight)
    if (not np.isfinite(treeheight)) or (treeheight <= 0):
        raise ToytreeError("treeheight must be a finite numeric value > 0.")

    names_seq = None if names is None else list(names)
    if names_seq is not None and len(names_seq) != ntips:
        raise ValueError(f"len(names)={len(names_seq)} does not match ntips={ntips}.")

    # seed generator
    rng = np.random.default_rng(seed)

    # generate random topology with N tips
    tree = rtree(
        ntips=ntips,
        random_names=random_names,
        seed=rng.integers(0, 2**31),
        names=names_seq,
    )

    # extend terminal edges to align, scale total height
    tree.mod.edges_scale_to_root_height(treeheight, inplace=True)
    tree.mod.edges_extend_tips_to_align(inplace=True)
    return tree


def imbtree(
    ntips: int ,
    treeheight: float = 1.0,
    random_names: bool = False,
    seed: Optional[int] = None,
    names: Optional[Iterable] = None,
) -> ToyTree:
    """Return an imbalanced (ladder-like) tree topology.

    Parameters
    ----------
    ntips: int
        The number of tips in the tree.
    treeheight: float
        All nodes in the tree will be scaled to retain relative node
        heights when scaling the total tree height to a new age.
    random_names: bool
        If True then names on the tips are randomized, else they are
        set to match with the node idx order.
    seed: Optional[int]
        An integer seed for the np random number generator.
    names: Optional[Iterable]
        Optional tip labels. If provided, its length must equal ``ntips``.
        Names are assigned in idx order unless ``random_names=True``.

    Example
    -------
    >>> tree = toytree.rtree.imbtree(ntips=10, seed=123)
    """
    if isinstance(ntips, bool) or not isinstance(ntips, int):
        raise ToytreeError("ntips must be an integer >= 2.")
    if ntips < 2:
        raise ToytreeError("ntips must be >= 2.")
    if isinstance(treeheight, bool) or not isinstance(treeheight, (int, float, np.number)):
        raise ToytreeError("treeheight must be a numeric value > 0.")
    treeheight = float(treeheight)
    if (not np.isfinite(treeheight)) or (treeheight <= 0):
        raise ToytreeError("treeheight must be a finite numeric value > 0.")
    names_seq = None if names is None else list(names)
    if names_seq is not None and len(names_seq) != ntips:
        raise ValueError(f"len(names)={len(names_seq)} does not match ntips={ntips}.")

    # generate random topology with N tips.
    root = Node()
    tip = root

    # add children n-1 times
    for _ in range(ntips - 1):
        child0 = Node(dist=1.)
        child1 = Node(dist=1.)
        tip._add_child(child0)
        tip._add_child(child1)
        tip = child0

    # will ladderize the tree and assign names and idxs
    tree = ToyTree(root)
    tree.mod.edges_extend_tips_to_align(inplace=True)
    tree.mod.edges_scale_to_root_height(treeheight, inplace=True)

    # randomize names
    _assign_names(tree, random_names, np.random.default_rng(seed), names=names_seq)
    return tree


def baltree(
    ntips: int,
    treeheight: float = 1.0,
    random_names: bool = False,
    seed: Optional[int] = None,
    names: Optional[Iterable] = None,
) -> ToyTree:
    """Return a balanced tree topology.

    Raises an error in ntips is not an even number.

    Parameters
    ----------
    ntips: int
        The number of tips in the tree.
    treeheight: float
        All nodes in the tree will be scaled to retain relative node
        heights when scaling the total tree height to a new age.
    random_names: bool
        If True then names on the tips are randomized, else they are
        set to match with the node idx order.
    seed: Optional[int]
        An integer seed for the np random number generator.
    names: Optional[Iterable]
        Optional tip labels. If provided, its length must equal ``ntips``.
        Names are assigned in idx order unless ``random_names=True``.

    Example
    -------
    >>> tree = toytree.rtree.baltree(ntips=10, seed=123)
    """
    if isinstance(ntips, bool) or not isinstance(ntips, int):
        raise ToytreeError("ntips must be an integer >= 2.")
    if ntips < 2:
        raise ToytreeError("ntips must be >= 2.")
    if isinstance(treeheight, bool) or not isinstance(treeheight, (int, float, np.number)):
        raise ToytreeError("treeheight must be a numeric value > 0.")
    treeheight = float(treeheight)
    if (not np.isfinite(treeheight)) or (treeheight <= 0):
        raise ToytreeError("treeheight must be a finite numeric value > 0.")
    names_seq = None if names is None else list(names)
    if names_seq is not None and len(names_seq) != ntips:
        raise ValueError(f"len(names)={len(names_seq)} does not match ntips={ntips}.")

    # in the construction algorithm below I store 'dist' values for
    # each node as the node distance from the root, to evenly create
    # splits. 'dists' are later overwritten by extend_tips_to_align.

    # check that ntips is even, if not raise an error
    if ntips % 2 != 0:
        raise ToytreeError("Number of tips must be even to make a balanced tree!")

    # get a root Node and keep track of nancestors
    root = Node()

    # add children n-1 times. Visits leaf nodes
    curtips = 0
    while curtips < ntips - 1:

        # get node from smaller subtree
        parent = _get_small_child(root)

        # add children to the selected node and store
        child0 = Node(dist=1.)
        child1 = Node(dist=1.)

        # remove parent from dict
        parent._add_child(child0)
        parent._add_child(child1)
        curtips += 1

    # align tips, optionally set a to a height, add names, and return
    tree = ToyTree(root)
    tree.mod.edges_extend_tips_to_align(inplace=True)
    tree.mod.edges_scale_to_root_height(treeheight, inplace=True)
    _assign_names(tree, random_names, np.random.default_rng(seed), names=names_seq)
    return tree


def bdtree(
    ntips: int = 10,
    time: float = 4,
    b: float = 1,
    d: float = 0,
    stop: str = "taxa",
    seed: Optional[int] = None,
    retain_extinct: bool = False,
    random_names: bool = False,
    names: Optional[Iterable] = None,
    verbose: bool = False,
) -> ToyTree:
    """Return a parametric birth/death tree.

    The tree is generated by randomly sampling birth or death events
    starting from a single ancestor until a stopping criterion is
    reached. If the tree goes extinct it is restarted.

    The waiting time to the next speciation event is exponential with
    parameter `b`; the waiting time to the next extinction event
    is exponential with parameter `d`. Only one or the other will
    be the next event. The waiting time to the next event (either type)
    is exponential with parameter b+d. The probability that an event
    is speciation is b/(b + d), extinction d/(b + d).

    Parameters
    ----------
    ntips: int
        Number of tips to generate for 'taxa' stopping criterion.
    time: float
        Amount of time to simulate for 'time' stopping criterion.
    b: float
        Birth rate per time unit
    d: death
        Death rate per time unit (d=0 produces Yule trees)
    stop: str
        Stopping critereon. Valid values are only 'taxa' or 'time'.
    seed: Optional[int]
        Random number generator seed.
    retain_extinct: bool
        If True, extinct lineages are retained in the returned tree and
        marked with ``node.extinct=True``.
    random_names: bool
        Whether to randomize tip names or name them in order.
    names: Optional[Iterable]
        Optional tip labels for extant tips in the returned tree. This is
        only supported for ``stop='taxa'`` and must have length ``ntips``.
    verbose: bool
        Sets logging level to INFO to show statistics

    Examples
    --------
    >>> rtre = toytree.rtree.bdtree(ntips=10, b=1.0, d=0.5)
    """
    # require an appropriate option for stopping
    if stop not in ["taxa", "time"]:
        raise ToytreeError("stop must be either 'taxa' or 'time'")
    if (b < 0) or (d < 0):
        raise ToytreeError("birth (b) and death (d) rates must both be >= 0.")
    if (b + d) == 0:
        raise ToytreeError("birth (b) and death (d) rates cannot both be 0.")
    names_seq = None if names is None else list(names)
    if stop == "taxa":
        if isinstance(ntips, bool) or (not isinstance(ntips, int)) or (ntips < 2):
            raise ToytreeError("for stop='taxa', ntips must be an integer >= 2.")
        if names_seq is not None and len(names_seq) != ntips:
            raise ValueError(f"len(names)={len(names_seq)} does not match ntips={ntips}.")
    else:
        if isinstance(time, bool) or (not isinstance(time, (int, float, np.number))):
            raise ToytreeError("for stop='time', time must be a finite numeric value > 0.")
        if (not np.isfinite(float(time))) or (float(time) <= 0):
            raise ToytreeError("for stop='time', time must be a finite numeric value > 0.")
        if names_seq is not None:
            raise ToytreeError("names are only supported when stop='taxa'.")

    # random generator
    rng = np.random.default_rng(seed)

    taxa_stop = ntips
    time_stop = float(time)

    # start from random tree (idxs will be re-assigned at end)
    root = Node(name="0")
    root._tdiv = 0

    # counters for extinctions, total events, and time
    resets = 0
    ext = 0
    evnts = 0
    time = 0.0

    # keep track of current leaf Nodes
    tips = [root]

    # continue until stop var
    while 1:

        # sample time until next event, increment t and events
        dtime = float(rng.exponential(1 / (len(tips) * (b + d))))
        time += dtime
        evnts += 1

        # advance branch lengths of all extant lineages up to this event time.
        for etip in tips:
            etip._dist += dtime

        # sample a [0-1] to choose birth or death and sample a tip node.
        rvar = float(rng.random())
        tip = rng.choice(tips)

        # event is a birth
        if rvar <= b / (b + d):
            # add child 1
            child1 = Node(name=f"{evnts}-1", dist=0)
            child1._tdiv = time
            tip._add_child(child1)
            # add child 2
            child2 = Node(f"{evnts}-2", dist=0)
            child2._tdiv = time
            tip._add_child(child2)
            # update tip list
            tips.extend([child1, child2])
            tips.remove(tip)

        # else event is extinction
        else:
            # drop the extinct lineage from the active tip list.
            tips.remove(tip)
            setattr(tip, "extinct", True)

            # Optionally prune extinct lineages from the reconstructed tree.
            if not retain_extinct:
                sisters = tip.get_sisters()
                if sisters:
                    tip.up._remove_child(tip)
                else:
                    while 1:
                        if tip.is_leaf() and not tip.is_root():
                            unary_node = tip
                            tip = tip.up
                            tip._remove_child(unary_node)
                        else:
                            break

            # If all extant lineages are extinct then restart simulation.
            if not tips:
                resets += 1
                ext = 0
                evnts = 0
                time = 0.0
                root = Node(name="0")
                root._tdiv = 0.0
                tips = [root]
                continue

            # advance extinction counter
            ext += 1

        # check stopping criterion
        if stop == "taxa":
            if len(tips) >= taxa_stop:
                break
        else:
            if time >= time_stop:
                break

    # log statistics
    if verbose:
        births = evnts - ext
        results = pd.Series({
            'time': time,
            'ntips': len(tips),
            'b': births,
            'd': ext,
            'b/d': np.inf if ext == 0 else births / ext,
            'resets': resets,
        })
        print(results)

    # if not retain_extinct then remove all internal unary nodes
    if not retain_extinct:
        # remove any unary nodes
        nodes = list(root._traverse_idxorder())
        for node in nodes[:-1]:
            if not node.is_leaf():
                if len(node.children) < 2:
                    node._delete(True, False)
        # make root the deepest node containing a split.
        while 1:
            if len(root.children) == 1:
                root = root.children[0]
            else:
                break

    # update coords and return
    # tre = tre.mod.ladderize()
    tree = ToyTree(root)
    _assign_names(tree, random_names, rng, names=names_seq)
    return tree


def coaltree(
    k: int,
    N: int = 100,
    seed: Optional[int] = None,
    random_names: bool = False,
    names: Optional[Iterable] = None,
) -> ToyTree:
    """Return a random ToyTree generated under the n-coalescent.

    Waiting times between coal events under the n-coalescent are
    exponentially distributed with rate 4N / (k * k-1). A tree is
    constructed by randomly sampling waiting times from an exponential
    distribution at each value of k from k to 1, and randomly joining
    Nodes at each coalescent interval.

    Note
    ----
    The E[Tmrca] (expected root height) is 4N.

    Parameters
    ----------
    k: int
        The number of tips (e.g., gene copies) sampled at the present.
    N: int
        The diploid effective population size (Ne). Here this only
        acts only as a scalar multiplier of the branch lengths, but
        does not change their relative distribution, which is
        determined solely by the number of nodes between each
        coalescent event (i.e., the coalescent).
    seed: int or None
        A seed for the numpy random number generator.
    random_names: bool
        Whether to randomize tip names or name them in order.
    names: Optional[Iterable]
        Optional tip labels. If provided, its length must equal ``k``.
        Names are assigned in idx order unless ``random_names=True``.
    """
    if isinstance(k, bool) or not isinstance(k, int):
        raise ToytreeError("k must be an integer >= 2.")
    if k < 2:
        raise ToytreeError("k must be >= 2.")
    if isinstance(N, bool) or not isinstance(N, (int, float, np.number)):
        raise ToytreeError("N must be a finite numeric value > 0.")
    N = float(N)
    if (not np.isfinite(N)) or (N <= 0):
        raise ToytreeError("N must be a finite numeric value > 0.")
    names_seq = None if names is None else list(names)
    if names_seq is not None and len(names_seq) != k:
        raise ValueError(f"len(names)={len(names_seq)} does not match k={k}.")

    # seed rng
    rng = np.random.default_rng(seed)

    # active lineages initialized as k sampled tips at present.
    nodes = [Node() for _ in range(k)]

    # iterate backwards in lineage count until one ancestor remains.
    for nlineages in range(k, 1, -1):
        # waiting time to next coalescent event in generations.
        wait = float(rng.exponential((4.0 * N) / (nlineages * (nlineages - 1))))

        # all extant lineages persist for this interval.
        for node in nodes:
            node._dist += wait

        # choose two lineages uniformly without replacement and coalesce them.
        i = int(rng.integers(0, len(nodes)))
        node0 = nodes.pop(i)
        j = int(rng.integers(0, len(nodes)))
        node1 = nodes.pop(j)
        parent = Node()
        parent._add_child(node0)
        parent._add_child(node1)
        nodes.append(parent)

    tree = ToyTree(nodes[0])
    _assign_names(tree, random_names, rng, names=names_seq)
    return tree


def _get_small_child(node):
    """Return the smaller of the descendant subclades of a node.

    A recursive for building balanced trees.
    """
    if not node.children:
        return node
    ldesc, rdesc = (len(i.get_leaves()) for i in node.children)
    if ldesc < rdesc:
        return _get_small_child(node.children[0])
    return _get_small_child(node.children[1])



if __name__ == "__main__":

    TREE = rtree(10)
    print(TREE.get_tip_labels())

    TREE = unittree(10)
    print(TREE.get_tip_labels())

    TREE = bdtree(10, b=0.5, d=0.5, verbose=1)
    # TREE._draw_browser()
    # print(TREE.get_tip_labels())
    # print(TREE.treenode.draw_ascii())

    # TREE = bdtree(10)
    # print(TREE.get_tip_labels())

    # sim_trees = [
    #     toytree.rtree.rtree(10),
    #     toytree.rtree.baltree(10),
    #     toytree.rtree.imbtree(10),
    #     toytree.rtree.bdtree(10),
    #     toytree.rtree.unittree(10),
    # ]
    # print(sim_trees)
