#!/usr/bin/env python

"""Counting utilities for phylogenetic tree space.

This module provides exact combinatorial counts for common tree-space quantities,
including numbers of bifurcating trees, multifurcating trees, subtrees, and
ranked histories.

The methods distinguish among related objects:
- bifurcating trees (fully resolved topology counts),
- multifurcating trees (topologies with at least one polytomy),
- labeled histories (ranked labeled trees), and
- unlabeled histories (ranked tree-shape histories).

References
----------
- Edwards AWF. 1970. Estimation of the branch points of a branching diffusion
  process. Journal of the Royal Statistical Society Series B 32:155-174.
- Harding EF. 1971. The probabilities of rooted tree-shapes generated by
  random bifurcation. Advances in Applied Probability 3:44-77.
- Brown JKM. 1994. Probabilities of evolutionary trees. Systematic Biology
  43:78-91.
- Aldous DJ. 2001. Stochastic models and descriptive statistics for
  phylogenetic trees, from Yule to today. Statistical Science 16:23-34.
- Steel M, McKenzie A. 2001. Properties of phylogenetic trees generated by
  Yule-type speciation models. Mathematical Biosciences 170:91-112.
- Felsenstein J. 2004. Inferring Phylogenies. Sinauer Associates.
"""

from math import comb, factorial, prod
from typing import Union

from toytree.core import ToyTree
from toytree.core.apis import TreeEnumAPI, add_subpackage_method

__all__ = [
    "get_num_bifurcating_trees",
    "get_num_multifurcating_trees",
    "get_num_quartets",
    "get_num_subtrees",
    "get_num_labeled_histories",
    "get_num_unlabeled_histories",
    "get_num_labeled_partitions",
]


def _get_num_places_a_tip_can_be_added(ntips: int, rooted: bool = True) -> int:
    """Return the number of insertion positions for adding one tip.

    Parameters
    ----------
    ntips : int
        Number of tips in the current tree before adding a new tip.
    rooted : bool, default=True
        If True, use rooted-tree insertion positions. If False, use unrooted.

    Returns
    -------
    int
        Number of branch positions where a new tip can be inserted.
    """
    if not isinstance(ntips, int) or isinstance(ntips, bool):
        raise TypeError("ntips must be an int.")
    if not rooted:
        return 2 * (ntips + 1) - 5
    return 2 * (ntips + 1) - 3


def _get_num_bifurcating_trees_by_successive_odds(
    ntips: int,
    rooted: bool = True,
) -> int:
    """Return number of labeled bifurcating trees by insertion-product counting.

    Parameters
    ----------
    ntips : int
        Number of tips.
    rooted : bool, default=True
        If True, count rooted trees. If False, count unrooted trees.

    Returns
    -------
    int
        Exact number of labeled bifurcating trees.

    Raises
    ------
    ValueError
        If `ntips` is too small for the requested rooting mode.

    Notes
    -----
    This uses the successive odd-product representation discussed in
    Felsenstein (2004).
    """
    min_tips = 2 if rooted else 3
    if ntips < min_tips:
        mode = "rooted" if rooted else "unrooted"
        raise ValueError(f"ntips must be >= {min_tips} for {mode} trees.")

    successive_odds = (
        _get_num_places_a_tip_can_be_added(i, rooted=rooted) for i in range(2, ntips)
    )
    return prod(successive_odds)


def _coerce_ntips(ntips: Union[int, ToyTree], min_tips: int) -> int:
    """Return integer tip count from int-or-tree input."""
    if isinstance(ntips, ToyTree):
        ntips = ntips.ntips
    if not isinstance(ntips, int) or isinstance(ntips, bool):
        raise TypeError("ntips must be an int or ToyTree.")
    if ntips < min_tips:
        raise ValueError(f"ntips must be >= {min_tips}.")
    return ntips


def _get_multifurcating_counts_matrix(ntips: int) -> list[list[int]]:
    """Return DP table of labeled rooted trees by (internal nodes, tips).

    The recurrence follows Felsenstein (2004), where `T[m, n]` is the number
    of rooted labeled trees with `n` tips and `m` internal nodes.
    """
    matrix = [[0 for _ in range(ntips + 1)] for _ in range(ntips)]

    for n_tips in range(2, ntips + 1):
        matrix[1][n_tips] = 1

    for n_tips in range(2, ntips + 1):
        for n_internal in range(2, n_tips):
            if n_internal == n_tips - 1:
                matrix[n_internal][n_tips] = get_num_bifurcating_trees(
                    n_tips, rooted=True
                )
            else:
                matrix[n_internal][n_tips] = (n_tips + n_internal - 2) * matrix[
                    n_internal - 1
                ][n_tips - 1] + n_internal * matrix[n_internal][n_tips - 1]
    return matrix


def get_num_bifurcating_trees(ntips: int, rooted: bool = True) -> int:
    """Return number of labeled bifurcating trees for a tip count.

    Parameters
    ----------
    ntips : int
        Number of tips in the tree.
    rooted : bool, default=True
        If True, count rooted trees. If False, count unrooted trees.

    Returns
    -------
    int
        Exact number of labeled bifurcating trees.

    Raises
    ------
    ValueError
        If `ntips` is too small for the requested rooting mode.

    Notes
    -----
    Rooted:
    ``(2n - 3)! / (2^(n - 2) * (n - 2)!)``

    Unrooted:
    ``(2n - 5)! / (2^(n - 3) * (n - 3)!)``

    Examples
    --------
    >>> get_num_bifurcating_trees(5, rooted=True)
    105
    >>> get_num_bifurcating_trees(5, rooted=False)
    15

    References
    ----------
    - Edwards (1970)
    - Felsenstein (2004)
    """
    min_tips = 2 if rooted else 3
    ntips = _coerce_ntips(ntips, min_tips=min_tips)
    return _get_num_bifurcating_trees_by_successive_odds(ntips=ntips, rooted=rooted)


def get_num_multifurcating_trees(
    ntips: int,
    n_internal_nodes: int | None = None,
    rooted: bool = True,
) -> int:
    """Return number of labeled trees with at least one multifurcation.

    Parameters
    ----------
    ntips : int
        Number of tips in the requested tree space.
    n_internal_nodes : int or None, default=None
        If provided, return count for this exact internal-node class.
        Counts corresponding to fully bifurcating trees are excluded from this
        method.
    rooted : bool, default=True
        If True, count rooted trees. If False, count unrooted trees using the
        standard rooted ``n-1`` reduction.

    Returns
    -------
    int
        Exact count of multifurcating trees for the selected class or total.

    Raises
    ------
    ValueError
        If inputs are outside valid ranges, or if `n_internal_nodes` requests
        the fully bifurcating class.

    Notes
    -----
    This uses the dynamic-programming recurrence described by Felsenstein
    (2004) for counts indexed by number of internal nodes.

    Examples
    --------
    >>> get_num_multifurcating_trees(5, rooted=True)
    131
    >>> get_num_multifurcating_trees(5, rooted=True, n_internal_nodes=2)
    25

    References
    ----------
    - Felsenstein (2004)
    """
    min_tips = 2 if rooted else 3
    ntips = _coerce_ntips(ntips, min_tips=min_tips)

    # Unrooted counts are obtained by reducing to rooted counts on n-1 tips.
    ntips_eff = ntips if rooted else ntips - 1
    max_internal = ntips_eff - 1
    matrix = _get_multifurcating_counts_matrix(ntips_eff)

    if n_internal_nodes is None:
        if max_internal <= 1:
            return 0
        return sum(matrix[m][ntips_eff] for m in range(1, max_internal))

    if not isinstance(n_internal_nodes, int) or isinstance(n_internal_nodes, bool):
        raise TypeError("n_internal_nodes must be an int or None.")
    if n_internal_nodes < 1 or n_internal_nodes > max_internal:
        raise ValueError(f"n_internal_nodes must be in [1, {max_internal}].")
    if n_internal_nodes == max_internal:
        raise ValueError(
            "n_internal_nodes corresponds to fully bifurcating trees; use "
            "get_num_bifurcating_trees for that class."
        )
    return matrix[n_internal_nodes][ntips_eff]


@add_subpackage_method(TreeEnumAPI)
def get_num_quartets(ntips: Union[int, ToyTree]) -> int:
    """Return number of distinct 4-tip subsets from a tree.

    Parameters
    ----------
    ntips : int or ToyTree
        Number of tips, or a tree from which tip count is read.

    Returns
    -------
    int
        Number of quartets, ``C(ntips, 4)``.

    Examples
    --------
    >>> get_num_quartets(10)
    210
    >>> tree = toytree.rtree.unittree(10, seed=123)
    >>> get_num_quartets(tree)
    210
    """
    ntips = _coerce_ntips(ntips, min_tips=1)
    if ntips < 4:
        return 0
    return comb(ntips, 4)


@add_subpackage_method(TreeEnumAPI)
def get_num_subtrees(ntips: Union[int, ToyTree], subtree_size: int) -> int:
    """Return number of distinct `subtree_size`-tip subsets from a tree.

    Parameters
    ----------
    ntips : int or ToyTree
        Number of tips, or a tree from which tip count is read.
    subtree_size : int
        Number of tips in each sampled subset.

    Returns
    -------
    int
        Number of subsets, ``C(ntips, subtree_size)``.

    Raises
    ------
    ValueError
        If `subtree_size` is less than 1.

    Examples
    --------
    >>> get_num_subtrees(10, 4)
    210
    >>> get_num_subtrees(10, 3)
    120
    """
    ntips = _coerce_ntips(ntips, min_tips=1)
    if not isinstance(subtree_size, int) or isinstance(subtree_size, bool):
        raise TypeError("subtree_size must be an int.")
    if subtree_size < 1:
        raise ValueError("subtree_size must be >= 1.")
    if subtree_size > ntips:
        return 0
    return comb(ntips, subtree_size)


def get_num_labeled_histories(ntips: int, rooted: bool = True) -> int:
    r"""Return number of ranked labeled histories for `ntips`.

    Parameters
    ----------
    ntips : int
        Number of tips in the tree.
    rooted : bool, default=True
        If True, count rooted histories. If False, count unrooted histories
        using rooted reduction on ``ntips - 1``.

    Returns
    -------
    int
        Number of ranked labeled histories.

    Raises
    ------
    ValueError
        If `ntips` is too small for the requested rooting mode.

    Note
    ----
    This count refers to ranked labeled histories, not merely unlabeled tree
    shapes with tip names attached.

    References
    ----------
    - Edwards (1970)
    - Harding (1971)
    - Brown (1994)

    Examples
    --------
    >>> get_num_labeled_histories(5)
    180
    >>> get_num_labeled_histories(6, rooted=False)
    180
    """
    min_tips = 1 if rooted else 2
    ntips = _coerce_ntips(ntips, min_tips=min_tips)
    ntips_eff = ntips if rooted else ntips - 1
    return (factorial(ntips_eff) * factorial(ntips_eff - 1)) // (2 ** (ntips_eff - 1))


def get_num_unlabeled_histories(ntips: int, rooted: bool = True) -> int:
    r"""Return number of ranked unlabeled histories for `ntips`.

    Parameters
    ----------
    ntips : int
        Number of tips in the tree.
    rooted : bool, default=True
        If True, count rooted histories. If False, count unrooted histories
        using rooted reduction on ``ntips - 1``.

    Returns
    -------
    int
        Number of ranked unlabeled histories.

    Raises
    ------
    ValueError
        If `ntips` is too small for the requested rooting mode.

    Notes
    -----
    The recurrence sums all bipartitions of `n` tips into `k` and `n-k`,
    weighted by ranked interleavings ``C(n-2, k-1)``. Equal-size splits are
    handled with combination-with-repetition weighting.

    References
    ----------
    - Harding (1971)
    - Brown (1994)

    Examples
    --------
    >>> get_num_unlabeled_histories(6)
    24
    >>> get_num_unlabeled_histories(7, rooted=False)
    24
    """
    min_tips = 1 if rooted else 2
    ntips = _coerce_ntips(ntips, min_tips=min_tips)
    ntips_eff = ntips if rooted else ntips - 1

    histories = [0] * (ntips_eff + 1)
    histories[1] = 1

    for n_tips in range(2, ntips_eff + 1):
        total = 0
        for left_size in range(1, n_tips // 2 + 1):
            right_size = n_tips - left_size
            interleavings = comb(n_tips - 2, left_size - 1)
            left_count = histories[left_size]
            right_count = histories[right_size]

            if left_size != right_size:
                total += interleavings * left_count * right_count
            else:
                total += interleavings * left_count * (left_count + 1) // 2
        histories[n_tips] = total
    return histories[ntips_eff]


def get_num_labeled_partitions(ntips: int, min_size: int = 2) -> int:
    """Return number of labeled two-way partitions under a size constraint.

    Parameters
    ----------
    ntips : int
        Number of labeled samples.
    min_size : int, default=2
        Minimum allowed group size on each side of the partition.

    Returns
    -------
    int
        Number of unlabeled splits of the `ntips` labels into two groups with
        both groups size >= `min_size`.

    Raises
    ------
    ValueError
        If `ntips` or `min_size` are out of valid range.

    Examples
    --------
    >>> toytree.enum.get_num_labeled_partitions(5)
    10
    >>> toytree.enum.get_num_labeled_partitions(6, min_size=3)
    10
    >>> toytree.enum.get_num_labeled_partitions(40)
    549755813847

    See Also
    --------
    - toytree.enum.iter_bipartitions
    """
    ntips = _coerce_ntips(ntips, min_tips=2)
    if not isinstance(min_size, int) or isinstance(min_size, bool):
        raise TypeError("min_size must be an int.")
    if min_size < 1:
        raise ValueError("min_size must be >= 1.")
    if ntips < 2 * min_size:
        return 0

    total_ways = sum(
        comb(ntips, size) for size in range(min_size, ntips - min_size + 1)
    )
    return total_ways // 2


if __name__ == "__main__":
    print(get_num_quartets(10))
    print(get_num_labeled_partitions(15))
